name: ROS CNIP list

on:
  workflow_dispatch:
  schedule:
    - cron: 30 6 * * *

jobs:
  ROS-IP-UPDATE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#        with:
#          token: ${{ secrets.ACTION_TOKEN }}
      - name: ros_cn_ip_update
        run: |
          bash -x script/update.sh
      - name: Push
        id: list-push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update ros-cnip-rsc
          skip_dirty_check: false
          commit_user_name: Action Bot
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: Action <actions@github.com>
